export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black min-h-screen font-sans">{children}</body>
    </html>
  )
}
